#!/bin/bash

set -e
set -u

function on_exit() {
    [ -e ${TEMPDIR} ] && rm -rf ${TEMPDIR}
}

function usage() {
    echo "mkcbundle [args]"
    echo
    echo "Valid args:"
    echo " -p <profile>    use a specific profile directory"
    echo " -v <version>    use a specific version (default to date)"
    echo
}


PROFILE=""
BUILD_NUMBER=$(date +%Y%m%d%H%M)

while getopts "p:v:" OPTION; do
    case ${OPTION} in
        p)
            PROFILE=${OPTARG}
            ;;
        v)
            BUILD_NUMBER=${OPTARG}
            ;;
        ?)
            usage
            exit 1
    esac
done

if [ "${PROFILE}" = "" ]; then
    usage
    exit 1
fi

if [ ! -f ${PROFILE}/manifest.txt ]; then
    echo "Cannot find profile: (${PROFILE}/manifest.txt missing)"
    exit 1
fi

TEMPDIR=$(mktemp -d --tmpdir bundler-XXXXXXXXXXX)
# trap on_exit exit

OLD_PKG_CONFIG_PATH=${PKG_CONFIG_PATH}
export PKG_CONFIG_PATH=${TEMPDIR}/${PROFILE}-${BUILD_NUMBER}/lib/pkgconfig:${OLD_PKG_CONFIG_PATH}

while read repo branch; do
    project=$(basename ${repo})
    echo -e "\n######################################################"
    echo "Building ${project}"
    echo -e "######################################################\n"

    git clone ${repo} ${TEMPDIR}/${project}
    pushd ${TEMPDIR}/${project}

    git checkout ${branch}

    if [ -x autogen.sh ]; then 
        ./autogen.sh
    else
        autoreconf -fi
    fi

    DESTDIR=${TEMPDIR}/${PROFILE}-${BUILD_NUMBER}

    ./configure CFLAGS=-I${DESTDIR}/include LDFLAGS=-L${DESTDIR}/lib --prefix=''
    make V=1
    # make check
    make DESTDIR=${DESTDIR} install

    popd

    # whack the .la files
    find ${DESTDIR} -name "*la" -exec rm {} \;
done < <( grep -v "^#" ${PROFILE}/manifest.txt )

rm -rf "${DESTDIR}/etc"
rm -rf "${DESTDIR}/init"

cp -a "${PROFILE}/etc" "${DESTDIR}"
cp -a "${PROFILE}/init" "${DESTDIR}"

tar -C ${TEMPDIR} -czvf ${PROFILE}-${BUILD_NUMBER}.tar.gz ${PROFILE}-${BUILD_NUMBER}

